### ISSUE TITLE
Refresh Controller?

### ISSUE THREAD

**Issue by shoxter** [aagarwal1012/Liquid-Pull-To-Refresh#11]
**Is your feature request related to a problem? Please describe.**
I'm unable to initiate a refresh externally (like upon navigating into a route, by clicking a button, etc)

**Describe the solution you'd like**
I would like for an optional "refresh controller" that allows for a refresh to be requested external to the LiquidPullToRefresh.

**Describe alternatives you've considered**
Currently using SmartRefresher to accomplish this but like the looks of this one better.

**Additional context**

**Comment by Taormina** [comment]
https://github.com/aagarwal1012/Liquid-Pull-To-Refresh/blob/master/lib/liquid_pull_to_refresh.dart#L547
https://github.com/aagarwal1012/Liquid-Pull-To-Refresh/blob/master/example/lib/main.dart#L64

Check out the example here, I'm pretty sure you can use your `GlobalKey<RefreshIndicatorState>` to call the `show()` method.

**Comment by shoxter** [comment]
I'll check it out and report back! Thanks!

**Comment by shoxter** [comment]
It looks like this will work. Thanks!
