### ISSUE TITLE
Pull up to refresh

### ISSUE THREAD

**Issue by jasonlaw** [aagarwal1012/Liquid-Pull-To-Refresh#16]
Is possible to have pull up to refresh? So instead of pulling from top to down, we would pull up from bottom to up. 
Please notes this is different from loading more data but to refresh/rebuild the data list.

Thanks in advance.

**Comment by leapit** [comment]
I think that's a good "load more" feature,otherwise,developer has to do some additional work based on this package for load more function

**Comment by aagarwal1012** [comment]
@jasonlaw, I think that the feature that you requested doesn't match the objective of this package so I am closing this issue for now. Feel free to reopen this issue if you want to add something.
