### ISSUE TITLE
DiagnosticsNode Compiler Error?

### ISSUE THREAD

**Issue by baltringer** [aagarwal1012/Liquid-Pull-To-Refresh#18]
**Is your feature request related to a problem? Please describe.**
I see some compiling error when trying to use the package. It looks like it has broken more than just this pckage.

**Describe the solution you'd like**
I have no clue. I just use the package not write them

**Additional context**
This is the compiler error:

file:///Users/brennan/flutter/.pub-cache/hosted/pub.dartlang.org/liquid_pull_to_refresh-1.1.0/lib/liquid_pull_to_refresh.dart:512:24: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/brennan/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
              context: 'when calling onRefresh',

**Comment by aagarwal1012** [comment]
@baltringer and @giandifra, actually this error is showing up in the latest `beta v1.6.7` of flutter. Once the `stable` version gets an update, then this issue will be resolved. Till then, you can make a change at `/lib/liquid_pull_to_refresh.dart:512:24`, just replace `context: 'when calling onRefresh',` with `context: ErrorDescription('when calling onRefresh'),`.
Thank you for raising this issue! 😄

**Comment by kekland** [comment]
@aagarwal1012 I think you should push the fix into the main branch, because the error is showing up in 1.6.3 too. I can add pull request if it is necessary.

**Comment by kekland** [comment]
@aagarwal1012 @baltringer I have added a pull request, you can see it here #20

**Comment by aagarwal1012** [comment]
@kekland, thank you for contributing 👍
