### ISSUE TITLE
Package does not work with AnimatedList

### ISSUE THREAD

**Issue by anthonysette** [aagarwal1012/Liquid-Pull-To-Refresh#24]
The package works great with lists but it would be nice to see functionality with the AnimatedList Widget

**Describe the solution you'd like**
Add ability to use Animated List.

**Describe alternatives you've considered**
I don't think there is an alternative apart from building list animations from scratch.

**Comment by aagarwal1012** [comment]
@anthonysette, 
`Liquid-pull-to-refresh` require `ScrollView` in the `child`, so give a  try to put the `AnimatedList` in the `CustomScrollView` and check if it works for now. 
Please give the status whether it works or not after you try the above suggestion.

**Comment by aagarwal1012** [comment]
@anthonysette, I am closing this issue for now. Feel free to reopen it if any problem arises.
