### ISSUE TITLE
Integration with FutureBuilder

### ISSUE THREAD

**Issue by Darklod** [aagarwal1012/Liquid-Pull-To-Refresh#25]

**Comment by aagarwal1012** [comment]
@Darklod, can you give a detailed description of this issue.

**Comment by khalifa007** [comment]
we cant build FutureBuilder  inside Liquid-Pull-To-Refresh widget !

**Comment by sam-parks** [comment]
The same goes for StreamBuilder and other edge cases like MediaQuery.removePadding.

**Comment by aagarwal1012** [comment]
#44 solves this issue!
