### ISSUE TITLE
Custom Liquid Effect Color

### ISSUE THREAD

**Issue by hasimyerlikaya** [aagarwal1012/Liquid-Pull-To-Refresh#38]
Hi,
Thank you for this package. I want to use it by changing the background color. But the fluid effect does not work properly. For example, when the ball falls down, the fluidity effect does not appear because background color is red. That effect color needs to be changed to background color. Would you do that, please?

I thing ClipPath must have background color. That same with background color option.

![Screenshot_2020-01-14-16-11-35-1](https://user-images.githubusercontent.com/7986394/72347244-bda15180-36e8-11ea-833b-192f79b557b1.png)

**Comment by AadumKhor** [comment]
@hasimyerlikaya Please share the code you used so that this can be replicated.

**Comment by AadumKhor** [comment]
Closing this issue because of no feedback. Feel free to reopen.
