### ISSUE TITLE
Maintainer Required

### ISSUE THREAD

**Issue by aagarwal1012** [aagarwal1012/Liquid-Pull-To-Refresh#41]
Due to multiple engagements and commitments, I am unable to devote time to solving issues and maintaining the package. Therefore, I strongly require someone who can spend his time to maintaining this repository.
Anyone interested can comment below and please start working on the current issues! In case of any difficultly, I am ready for a quick call to solve ambiguities.

**Comment by AadumKhor** [comment]
I am interested and I have also submitted a PR for you to check.

**Comment by aagarwal1012** [comment]
@AadumKhor, I have sent you a collaborator invite. I hope that you will maintain this package efficiently. 😃

**Comment by AadumKhor** [comment]
@aagarwal1012 Thank you. I'll accept the invite
