### ISSUE TITLE
Liquid pull to refresh for list<object>

### ISSUE THREAD

**Issue by fatimahmira** [aagarwal1012/Liquid-Pull-To-Refresh#48]
**Is your feature can use for list<object>? Please describe.**
I'm always frustrated when trying to showing my list<object>. it doesnt print any data. just empty on page. the error i was get was:
- I/flutter ( 4437): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#2182f NEEDS-LAYOUT NEEDS-PAINT
- I/flutter ( 4437): Another exception was thrown: Incorrect use of ParentDataWidget.
- I/flutter ( 4437): Another exception was thrown: Every child of a RenderCustomMultiChildLayoutBox must have an ID in its parent data.

please give me an example to showing list<object> using your packages.
thank you :)

**Comment by AadumKhor** [comment]
Hi @fatimahmira. Please post the code you're using that causes this issue.

**Comment by AadumKhor** [comment]
Closing this issue since there is no feedback. Feel free to reopen if and when needed.
