### ISSUE TITLE
Request add multi state features

### ISSUE THREAD

**Issue by thanhhuan1990** [aagarwal1012/Liquid-Pull-To-Refresh#5]
I think your solution is very good, it's look so pretty on my application. 
But I want to make a request for new feature: Multi state view

**Describe the solution you'd like**
As I understand about your solution, PullToRefresh just work for ListView with data, empty list will not show any information.
I hope you can support to add more state: Error, Empty. And user can still pull to refresh to retry or get new data from server in new state.
At this version, if I use another widget to show another state, user cannot perform another action with your animation.

Thanks and Best regards,
Thanh Huan

**Comment by aagarwal1012** [comment]
@thanhhuan1990, that for raising the issue, we will surely look upon it.

**Comment by MichaelSowah** [comment]
I really want to use it but my problem is the fact that I cant throw in any other child unless its a scrollview so when I wrap my scrollbar around it, I get an error....
