### ISSUE TITLE
LPTR depends on deprecated color selectors for coloration.

### ISSUE THREAD

**Issue by RemcoSchrijver** [aagarwal1012/Liquid-Pull-To-Refresh#60]
**Describe the bug**
Starting from Flutter 2.5.0 the usage of ThemeData.accentColor is deprecated and there is still a dependency on it, creating unexpected color behaviour when tryin to change colors starting from 2.5.0.

**To Reproduce**
1. Create a theme with the recommendend method of setting your Theme.colorScheme with ColorScheme.fromSwatch()
2. LPRT does not follow this coloring.

**Expected behavior**
LPTR to follow the coloring set int he ColorScheme field of the theme.

**Flutter:**
 - version 2.8.1
 - channel stable

**Additional context**
The dependency should be moved to the secondary color of the colorScheme property of Theme, see https://docs.flutter.dev/release/breaking-changes/theme-data-accent-properties

**Comment by aagarwal1012** [comment]
#61 fixes this issue.
