### ISSUE TITLE
Don't support reverse List ?

### ISSUE THREAD

**Issue by lipengda** [aagarwal1012/Liquid-Pull-To-Refresh#9]
Need to implement chat like functionality where last list item stays at the bottom of the screen on initial load and newly loaded items are added on top of that.

**Comment by aagarwal1012** [comment]
@lipengda, for doing that you can simply reverse the list before giving input to `listview`.

**Comment by valetanddama** [comment]
Doesn't work
`
LiquidPullToRefresh(
          key: _refreshIndicatorKey,
          showChildOpacityTransition: false,
          onRefresh: _handleRefresh,
          child: ListView.builder(
              controller: _messageScrollController,
              reverse: true,
              ...
          ),
)
`
displays not reverse list. Without LiquidPullToRefresh all work fine.
